language: go

go:
  - "1.x"

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - pip install --user awscli
  - go get -u ./...

script: GOOS=linux GOARCH=amd64 go build -o ./main ./src

deploy:
  provider: script
  script: zip -X -r ./upload.zip ./main && aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://upload.zip
