version: 2.1

executors: # a reusable executor
  aws:
    docker:
      - image: circleci/aws-cli@0.1.13
jobs:
  build-upload:
    executor: aws
    docker: 
      - image: circleci/golang:latest
    steps:
      - checkout
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: |
          go mod download
      - run: |
          GOOS=linux GOARCH=amd64 go build -o ./main ./src
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: |
          zip -X -r upload.zip main && aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://upload.zip
workflows:
  version: 2
  update-aws-lambda:
    jobs:
      - build-upload:
          filters:
            branches:
              only: master